### PR TITLE
zoom

### LINKED ISSUE #3: Zoom in / out
The graph is huge now, we need to zoom in & out like this:

http://bl.ocks.org/eyaler/10586116

Except that's d3 v3 and we're using d3 v4. This is also vaguely related, but mainly I just need to read the d3.zoom docs....

https://bl.ocks.org/rutgerhofste/5bd5b06f7817f0ff3ba1daa64dee629d

### PR DESCRIPTION
**Pull request by madwort**
* zooms in & out & pan
* will fix https://github.com/coreymwamba/uk-jazz-rhizome/issues/3
* slight UI bug - looks fine to start with then goes weird on first zoom, then acts as normal, may be a d3 bug?

### CODE REVIEW

**Comment by madwort** [comment]
uk-jazz-rhizome-zoom-wip

**Comment by madwort** [comment]
Ok, with the second commit, looking better, have to head out to a gig now...
uk-jazz-rhizome-zoom-wip-2

**Comment by madwort** [comment]
It looks good when it opens, then goes weird on the first attempt to zoom, then it's fine after that...

**Comment by madwort** [comment]
Just added a really neat feature - highlight a musician & it pans & zooms in on them!

**Comment by coreymwamba** [comment]
When the musician is highlighted, attempting to zoom (out) moves the centre of graph to the bottom left. But other than that, it's amazing!

**Pull request merged**
